matrix:
    include:
       - language: julia
         julia: 0.6
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: nightly
         os: linux
         dist: trusty
         sudo: false
       - language: julia
         julia: 0.6
         os: linux
       - language: julia
         julia: nightly
         os: linux

       - language: julia
         julia: 0.6
         os: osx
       - language: julia
         julia: nightly
         os: osx

    allow_failures:
       - julia: nightly
       
notifications:
    email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("HilbertSpaceFillingCurve"); Pkg.test("HilbertSpaceFillingCurve"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("HilbertSpaceFillingCurve")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
